Repository aha-app/faye-redis-sharded-node, pull requests merged in 2022-03, with the labels that each got.

#2 DEVOPS-1244: Fix sharding bug
  lib/faye-redis-sharded.js
Labels: Needs Code Review, Bug fix

#3 add ping command to createClient
  lib/faye-redis-sharded.js
Labels: Needs Code Review

#4 bump version
  package.json
Labels: Needs Code Review

#5 A-13686: Fix namespace references in faye sharded redis
  lib/faye-redis-sharded.js
  package.json
Labels: Needs Code Review, Support Fix
